FROM debian:bullseye-slim as slicd
RUN set -x && apt-get update \
    && apt-get install -y curl build-essential \
    && curl https://skarnet.org/software/skalibs/skalibs-2.3.10.0.tar.gz -o skalibs-2.3.10.0.tar.gz \
    && tar xf skalibs-2.3.10.0.tar.gz \
    && cd skalibs-2.3.10.0 \
    && ./configure \
    && make install \
    && cd .. \
    && curl https://jjacky.com/slicd/slicd-0.2.0.tar.gz -o slicd-0.2.0.tar.gz \
    && tar xf slicd-0.2.0.tar.gz \
    && cd slicd-0.2.0 \
    && ./configure \
    && make install

FROM debian:bullseye-slim as pgbackrest
RUN set -x && apt-get update \
    && apt-get install -y make gcc libpq-dev libssl-dev libxml2-dev pkg-config \
        liblz4-dev libzstd-dev libbz2-dev libz-dev libyaml-dev curl \
    && curl -L https://github.com/pgbackrest/pgbackrest/archive/release/2.36.tar.gz \
        -o pgbackrest-release-2.36.tar.gz \
    && tar xf pgbackrest-release-2.36.tar.gz \
    && cd pgbackrest-release-2.36/src \
    && ./configure \
    && make

FROM debian:bullseye-slim
COPY backups.sh ./
COPY pgbackrest-backups.conf /etc/pgbackrest/pgbackrest.conf
COPY --from=slicd /bin/slicd-* /bin/setuid /bin/miniexec /bin/
COPY crontab back-up.sh ./
COPY --from=pgbackrest pgbackrest-release-2.36/src/pgbackrest /usr/bin/
RUN set -x && apt-get update \
    && apt-get install -y postgresql-client libxml2 \
        ssh cifs-utils \
        curl wait-for-it pwgen \
    && mkdir -p -m 770 /var/log/pgbackrest \
    && mkdir /run/sshd \
    && set +x && echo "root:`pwgen -1`" | chpasswd && set -x \
    && slicd-parser -s crontab -o crontab.bin
CMD ["./backups.sh"]
