services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    init: yes
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      DONT_START_DB: $DONT_START_DB
    volumes:
      - db:/var/lib/postgresql/data
      - ./host-keys:/host-keys
      - ./id_rsa:/id_rsa
      - ./authorized_keys:/authorized_keys
      - ./known_hosts-db:/known_hosts
    ports:
      - $DB_PORT:5432
    networks:
      - db

  backups:
    build:
      context: .
      dockerfile: Dockerfile-backups
    init: yes
    volumes:
      - backups:/var/lib/pgbackrest
      - ./host-keys:/host-keys
      - ./id_rsa:/id_rsa
      - ./authorized_keys:/authorized_keys
      - ./known_hosts-backups:/known_hosts
    ports:
      - $BACKUPS_PORT:22
    networks:
      - db

volumes:
  db:
  backups:

networks:
  db:
    ipam:
      config:
        - subnet: 10.0.0.0/24
